# Generated by Django 3.2.17 on 2023-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(),
        ),
    ]
