# Generated by Django 3.2.17 on 2023-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230313_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_location',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
